title: Project
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: summary
            field:
              type: textarea
              display: Summary
          -
            handle: content
            field:
              type: markdown
              display: Content
              localizable: true
          -
            handle: live_link
            field:
              type: link
              display: 'Live Link'
          -
            handle: repo_link
            field:
              type: link
              display: 'Repo Link'
          -
            handle: recording_link
            field:
              type: link
              display: 'Recording Link'
          -
            handle: thumbnail
            field:
              container: assets
              type: assets
              display: Thumbnail
          -
            handle: author
            field:
              type: users
              display: Author
              default: current
              localizable: true
              max_items: 1
          -
            handle: template
            field:
              type: template
              display: Template
              localizable: true
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: date
            field:
              type: date
              required: true
              default: now
              validate:
                - required
          -
            handle: parent
            field:
              type: entries
              collections:
                - projects
              max_items: 1
              listable: false
              localizable: true
